// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj_0_FMeKC9FjEqx8Toz78wMimHMW2Pi0',
    appId: '1:552167690690:web:3853bcef081ce72aaf865b',
    messagingSenderId: '552167690690',
    projectId: 'controlecombustivel-da1c7',
    authDomain: 'controlecombustivel-da1c7.firebaseapp.com',
    storageBucket: 'controlecombustivel-da1c7.firebasestorage.app',
    measurementId: 'G-8YQ90K89R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2W5Iwu7IfwoYeeLI_Tw22gw68aJFBhcg',
    appId: '1:552167690690:android:45ab38f51a3decc5af865b',
    messagingSenderId: '552167690690',
    projectId: 'controlecombustivel-da1c7',
    storageBucket: 'controlecombustivel-da1c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3FOqoHYbKtW_KkACHefA5H1QRqR7_SBk',
    appId: '1:552167690690:ios:6633ce5c2749e374af865b',
    messagingSenderId: '552167690690',
    projectId: 'controlecombustivel-da1c7',
    storageBucket: 'controlecombustivel-da1c7.firebasestorage.app',
    iosBundleId: 'com.example.controleCombustivel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3FOqoHYbKtW_KkACHefA5H1QRqR7_SBk',
    appId: '1:552167690690:ios:6633ce5c2749e374af865b',
    messagingSenderId: '552167690690',
    projectId: 'controlecombustivel-da1c7',
    storageBucket: 'controlecombustivel-da1c7.firebasestorage.app',
    iosBundleId: 'com.example.controleCombustivel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj_0_FMeKC9FjEqx8Toz78wMimHMW2Pi0',
    appId: '1:552167690690:web:0052fb18131f7f0baf865b',
    messagingSenderId: '552167690690',
    projectId: 'controlecombustivel-da1c7',
    authDomain: 'controlecombustivel-da1c7.firebaseapp.com',
    storageBucket: 'controlecombustivel-da1c7.firebasestorage.app',
    measurementId: 'G-8PJBZG78MS',
  );
}
